name: Deploy AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_SHA: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/bush/project-sys:latest .
          docker build -t $ECR_REGISTRY/bush/project-sys:$IMAGE_SHA .

          docker push $ECR_REGISTRY/bush/project-sys:latest     
          docker push $ECR_REGISTRY/bush/project-sys:$IMAGE_SHA

      - name: Force ECS deployment
        run: |
          aws ecs update-service --cluster bush-project-cluster --service project-sys-service --force-new-deployment